CREATE TYPE "UserRole" AS ENUM ('admin', 'viewer_editor');
CREATE TYPE "ProviderType" AS ENUM ('simplefin', 'csv', 'plaid', 'demo');
CREATE TYPE "TransactionDirection" AS ENUM ('income', 'expense', 'transfer');
CREATE TYPE "SyncStatus" AS ENUM ('running', 'completed', 'failed');
CREATE TYPE "AuditAction" AS ENUM ('login', 'connection_added', 'connection_updated', 'connection_deleted', 'sync_started', 'sync_completed', 'sync_failed', 'category_changed', 'budget_changed');

CREATE TABLE "Household" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Household_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "name" TEXT NOT NULL, "username" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FinancialConnection" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "provider" "ProviderType" NOT NULL, "name" TEXT NOT NULL, "encryptedCredentials" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "lastSyncedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "FinancialConnection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "connectionId" TEXT NOT NULL, "name" TEXT NOT NULL, "officialName" TEXT, "type" TEXT NOT NULL, "subtype" TEXT, "mask" TEXT, "currentBalance" DECIMAL(12,2) NOT NULL DEFAULT 0, "availableBalance" DECIMAL(12,2), "currency" TEXT NOT NULL DEFAULT 'USD', "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Transaction" ("id" TEXT NOT NULL, "providerTransactionId" TEXT, "accountId" TEXT NOT NULL, "date" TIMESTAMP(3) NOT NULL, "postedDate" TIMESTAMP(3), "description" TEXT NOT NULL, "merchantName" TEXT, "originalDescription" TEXT, "amount" DECIMAL(12,2) NOT NULL, "direction" "TransactionDirection" NOT NULL, "categoryId" TEXT, "userReviewed" BOOLEAN NOT NULL DEFAULT false, "excludedFromBudget" BOOLEAN NOT NULL DEFAULT false, "notes" TEXT, "tags" TEXT[] DEFAULT ARRAY[]::TEXT[], "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "name" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT '#2563eb', "icon" TEXT NOT NULL DEFAULT 'circle', "isDefault" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CategoryRule" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "merchantContains" TEXT, "descriptionContains" TEXT, "amountEquals" DECIMAL(12,2), "amountGreaterThan" DECIMAL(12,2), "amountLessThan" DECIMAL(12,2), "accountId" TEXT, "excludeFromBudget" BOOLEAN NOT NULL DEFAULT false, "priority" INTEGER NOT NULL DEFAULT 100, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CategoryRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Budget" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "month" TIMESTAMP(3) NOT NULL, "planned" DECIMAL(12,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Budget_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BudgetMonth" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "month" TIMESTAMP(3) NOT NULL, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BudgetMonth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MerchantAlias" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "alias" TEXT NOT NULL, "canonical" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MerchantAlias_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SyncRun" ("id" TEXT NOT NULL, "connectionId" TEXT NOT NULL, "provider" "ProviderType" NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "endedAt" TIMESTAMP(3), "status" "SyncStatus" NOT NULL, "accountsSynced" INTEGER NOT NULL DEFAULT 0, "transactionsInserted" INTEGER NOT NULL DEFAULT 0, "transactionsUpdated" INTEGER NOT NULL DEFAULT 0, "errorMessage" TEXT, CONSTRAINT "SyncRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "userId" TEXT, "action" "AuditAction" NOT NULL, "entityType" TEXT, "entityId" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
CREATE UNIQUE INDEX "Account_connectionId_providerAccountId_key" ON "Account"("connectionId", "providerAccountId");
CREATE UNIQUE INDEX "Transaction_accountId_providerTransactionId_key" ON "Transaction"("accountId", "providerTransactionId");
CREATE INDEX "Transaction_date_idx" ON "Transaction"("date");
CREATE INDEX "Transaction_categoryId_idx" ON "Transaction"("categoryId");
CREATE UNIQUE INDEX "Category_householdId_name_key" ON "Category"("householdId", "name");
CREATE INDEX "CategoryRule_householdId_priority_idx" ON "CategoryRule"("householdId", "priority");
CREATE UNIQUE INDEX "Budget_householdId_categoryId_month_key" ON "Budget"("householdId", "categoryId", "month");
CREATE UNIQUE INDEX "BudgetMonth_householdId_month_key" ON "BudgetMonth"("householdId", "month");
CREATE UNIQUE INDEX "MerchantAlias_householdId_alias_key" ON "MerchantAlias"("householdId", "alias");
ALTER TABLE "User" ADD CONSTRAINT "User_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FinancialConnection" ADD CONSTRAINT "FinancialConnection_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "FinancialConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Category" ADD CONSTRAINT "Category_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CategoryRule" ADD CONSTRAINT "CategoryRule_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BudgetMonth" ADD CONSTRAINT "BudgetMonth_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MerchantAlias" ADD CONSTRAINT "MerchantAlias_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SyncRun" ADD CONSTRAINT "SyncRun_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "FinancialConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
